//Função para somar dois valores
    export  let somar = (a, b) => { return a + b};

//Função para subtrair dois valores
    export  let subtrair = (a, b) => { return a - b};

//Função para dividir dois valores
    export  let dividir = (a, b) => { return a / b};

//Função para multiplicar dois valores
    export  let multiplicar = (a, b) => { return a * b};

//Função para potenciação de um número
    export  let potencia = (a, b) => { return a ** b};

//Função para descobrir tantos porcento de um valor
    export  let calcularValorPorcentagem = (a, b) => { return (a / 100) * b }

//Função para descobrir porcentagem de um valor
    export  let calcularPorcentagemDoValor = (a, b) => { return (b / a) * 100 }
    